Abtract: load data
        +see imformation of data
        +drop sample duplicate

In [2]:
from pathlib import Path
import urllib.request
import tarfile
import zipfile
import pandas as pd

In [3]:
#LOAD DỮ LIỆU TỪ FILE ZIP
def load_data(zip_path, file_in_zip):
    with zipfile.ZipFile(Path(zip_path)) as z:
        with z.open(file_in_zip) as f:
            return pd.read_csv(f)
db=load_data("../../data/raw/data_kaggle_date.zip","diabetes_binary_5050split_health_indicators_BRFSS2015.csv")

In [4]:
db.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [5]:
db.shape

(70692, 22)

In [6]:
db.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [7]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_binary       70692 non-null  float64
 1   HighBP                70692 non-null  float64
 2   HighChol              70692 non-null  float64
 3   CholCheck             70692 non-null  float64
 4   BMI                   70692 non-null  float64
 5   Smoker                70692 non-null  float64
 6   Stroke                70692 non-null  float64
 7   HeartDiseaseorAttack  70692 non-null  float64
 8   PhysActivity          70692 non-null  float64
 9   Fruits                70692 non-null  float64
 10  Veggies               70692 non-null  float64
 11  HvyAlcoholConsump     70692 non-null  float64
 12  AnyHealthcare         70692 non-null  float64
 13  NoDocbcCost           70692 non-null  float64
 14  GenHlth               70692 non-null  float64
 15  MentHlth              70692 non-null  float64
 16  PhysHlth              70692 non-null  float64
 17  DiffWalk              70692 non-null  float64
 18  Sex                   70692 non-null  float64
 19  Age                   70692 non-null  float64
 20  Education             70692 non-null  float64
 21  Income                70692 non-null  float64
dtypes: float64(22)
memory usage: 11.9 MB

In [8]:
db["Diabetes_binary"].value_counts()

Diabetes_binary
0.0    35346
1.0    35346
Name: count, dtype: int64

In [9]:
for col in db.columns:
  print(f"{col} : {db[col].value_counts()}\n")

Diabetes_binary : Diabetes_binary
0.0    35346
1.0    35346
Name: count, dtype: int64

HighBP : HighBP
1.0    39832
0.0    30860
Name: count, dtype: int64

HighChol : HighChol
1.0    37163
0.0    33529
Name: count, dtype: int64

CholCheck : CholCheck
1.0    68943
0.0     1749
Name: count, dtype: int64

BMI : BMI
27.0    6327
26.0    4975
28.0    4583
24.0    4392
30.0    4344
        ...
85.0       1
83.0       1
80.0       1
78.0       1
74.0       1
Name: count, Length: 80, dtype: int64

Smoker : Smoker
0.0    37094
1.0    33598
Name: count, dtype: int64

Stroke : Stroke
0.0    66297
1.0     4395
Name: count, dtype: int64

HeartDiseaseorAttack : HeartDiseaseorAttack
0.0    60243
1.0    10449
Name: count, dtype: int64

PhysActivity : PhysActivity
1.0    49699
0.0    20993
Name: count, dtype: int64

Fruits : Fruits
1.0    43249
0.0    27443
Name: count, dtype: int64

Veggies : Veggies
1.0    55760
0.0    14932
Name: count, dtype: int64

HvyAlcoholConsump : HvyAlcoholConsump
0.0    67672
1.0     3020
Name: count, dtype: int64

AnyHealthcare : AnyHealthcare
1.0    67508
0.0     3184
Name: count, dtype: int64

NoDocbcCost : NoDocbcCost
0.0    64053
1.0     6639
Name: count, dtype: int64

GenHlth : GenHlth
3.0    23427
2.0    19872
4.0    13303
1.0     8282
5.0     5808
Name: count, dtype: int64

MentHlth : MentHlth
0.0     48091
30.0     4320
2.0      3267
5.0      2519
1.0      2051
3.0      1967
10.0     1924
15.0     1767
20.0     1125
4.0       981
7.0       825
25.0      425
14.0      353
6.0       288
8.0       198
12.0      130
28.0       99
21.0       84
29.0       53
18.0       42
16.0       28
9.0        28
22.0       22
17.0       18
26.0       17
27.0       17
13.0       15
23.0       13
24.0       10
11.0        8
19.0        7
Name: count, dtype: int64

PhysHlth : PhysHlth
0.0     39915
30.0     7953
2.0      4102
1.0      2853
3.0      2438
5.0      2332
10.0     1980
15.0     1913
4.0      1376
7.0      1326
20.0     1292
14.0      802
25.0      557
6.0       447
8.0       276
21.0      229
28.0      211
12.0      205
29.0       95
9.0        55
18.0       50
16.0       50
17.0       35
27.0       34
22.0       31
23.0       27
26.0       26
13.0       26
24.0       24
11.0       22
19.0       10
Name: count, dtype: int64

DiffWalk : DiffWalk
0.0    52826
1.0    17866
Name: count, dtype: int64

Sex : Sex
0.0    38386
1.0    32306
Name: count, dtype: int64

Age : Age
10.0    10856
9.0     10112
8.0      8603
11.0     8044
7.0      6872
13.0     5426
12.0     5394
6.0      4648
5.0      3520
4.0      2793
3.0      2049
2.0      1396
1.0       979
Name: count, dtype: int64

Education : Education
6.0    26020
5.0    20030
4.0    19473
3.0     3447
2.0     1647
1.0       75
Name: count, dtype: int64

Income : Income
8.0    20646
7.0    11425
6.0    10287
5.0     8010
4.0     6658
3.0     5557
2.0     4498
1.0     3611
Name: count, dtype: int64

In [10]:
db.isnull().sum()

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [11]:
db.describe().T

,count,mean,std,min,25%,50%,75%,max
Diabetes_binary,70692.0,0.500000,0.500004,0.0,0.0,0.5,1.0,1.0
HighBP,70692.0,0.563458,0.495960,0.0,0.0,1.0,1.0,1.0
HighChol,70692.0,0.525703,0.499342,0.0,0.0,1.0,1.0,1.0
CholCheck,70692.0,0.975259,0.155336,0.0,1.0,1.0,1.0,1.0
BMI,70692.0,29.856985,7.113954,12.0,25.0,29.0,33.0,98.0
Smoker,70692.0,0.475273,0.499392,0.0,0.0,0.0,1.0,1.0
Stroke,70692.0,0.062171,0.241468,0.0,0.0,0.0,0.0,1.0
HeartDiseaseorAttack,70692.0,0.147810,0.354914,0.0,0.0,0.0,0.0,1.0
PhysActivity,70692.0,0.703036,0.456924,0.0,0.0,1.0,1.0,1.0
Fruits,70692.0,0.611795,0.487345,0.0,0.0,1.0,1.0,1.0
Veggies,70692.0,0.788774,0.408181,0.0,1.0,1.0,1.0,1.0
HvyAlcoholConsump,70692.0,0.042721,0.202228,0.0,0.0,0.0,0.0,1.0
AnyHealthcare,70692.0,0.954960,0.207394,0.0,1.0,1.0,1.0,1.0
NoDocbcCost,70692.0,0.093914,0.291712,0.0,0.0,0.0,0.0,1.0
GenHlth,70692.0,2.837082,1.113565,1.0,2.0,3.0,4.0,5.0
MentHlth,70692.0,3.752037,8.155627,0.0,0.0,0.0,2.0,30.0
PhysHlth,70692.0,5.810417,10.062261,0.0,0.0,0.0,6.0,30.0
DiffWalk,70692.0,0.252730,0.434581,0.0,0.0,0.0,1.0,1.0
Sex,70692.0,0.456997,0.498151,0.0,0.0,0.0,1.0,1.0
Age,70692.0,8.584055,2.852153,1.0,7.0,9.0,11.0,13.0
Education,70692.0,4.920953,1.029081,1.0,4.0,5.0,6.0,6.0
Income,70692.0,5.698311,2.175196,1.0,4.0,6.0,8.0,8.0

In [11]:
#  KIỂM TRẢ HÀNG TRÙNG LẶP
db.duplicated().sum()

1635

In [12]:
#xóa các hàng trùng lặp
db.drop_duplicates(inplace=True)

In [13]:
db.shape

(69057, 22)

In [14]:
db['Diabetes'] = db['Diabetes_binary']
db.drop(columns = 'Diabetes_binary', inplace=True)

In [15]:
#Sau khi xóa save lại
db.to_csv("../../data/processed/database_drop_duplicates.csv",index=False)